// Named character references. The full HTML table has ~2,200 entries; this
// is the subset that shows up in real markup, plus numeric references.

export const ENTITIES = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
  ensp: " ",
  emsp: " ",
  thinsp: " ",
  zwnj: "‌",
  zwj: "‍",
  lrm: "‎",
  rlm: "‏",
  copy: "©",
  reg: "®",
  trade: "™",
  hellip: "…",
  mdash: "—",
  ndash: "–",
  lsquo: "‘",
  rsquo: "’",
  sbquo: "‚",
  ldquo: "“",
  rdquo: "”",
  bdquo: "„",
  laquo: "«",
  raquo: "»",
  lsaquo: "‹",
  rsaquo: "›",
  bull: "•",
  middot: "·",
  times: "×",
  divide: "÷",
  minus: "−",
  plusmn: "±",
  deg: "°",
  micro: "µ",
  para: "¶",
  sect: "§",
  cent: "¢",
  pound: "£",
  euro: "€",
  yen: "¥",
  curren: "¤",
  iexcl: "¡",
  iquest: "¿",
  shy: "­",
  macr: "¯",
  acute: "´",
  cedil: "¸",
  uml: "¨",
  ordf: "ª",
  ordm: "º",
  sup1: "¹",
  sup2: "²",
  sup3: "³",
  frac14: "¼",
  frac12: "½",
  frac34: "¾",
  not: "¬",
  brvbar: "¦",
  larr: "←",
  uarr: "↑",
  rarr: "→",
  darr: "↓",
  harr: "↔",
  lArr: "⇐",
  uArr: "⇑",
  rArr: "⇒",
  dArr: "⇓",
  hArr: "⇔",
  crarr: "↵",
  check: "✓",
  cross: "✗",
  star: "☆",
  starf: "★",
  hearts: "♥",
  spades: "♠",
  clubs: "♣",
  diams: "♦",
  infin: "∞",
  ne: "≠",
  le: "≤",
  ge: "≥",
  asymp: "≈",
  equiv: "≡",
  sum: "∑",
  prod: "∏",
  radic: "√",
  part: "∂",
  nabla: "∇",
  isin: "∈",
  notin: "∉",
  cap: "∩",
  cup: "∪",
  int: "∫",
  there4: "∴",
  prime: "′",
  Prime: "″",
  oline: "‾",
  frasl: "⁄",
  permil: "‰",
  dagger: "†",
  Dagger: "‡",
  loz: "◊",
  alpha: "α",
  beta: "β",
  gamma: "γ",
  delta: "δ",
  epsilon: "ε",
  lambda: "λ",
  mu: "μ",
  pi: "π",
  sigma: "σ",
  tau: "τ",
  phi: "φ",
  omega: "ω",
  Delta: "Δ",
  Sigma: "Σ",
  Omega: "Ω",
  Agrave: "À",
  Aacute: "Á",
  Acirc: "Â",
  Atilde: "Ã",
  Auml: "Ä",
  Aring: "Å",
  AElig: "Æ",
  Ccedil: "Ç",
  Egrave: "È",
  Eacute: "É",
  Ecirc: "Ê",
  Euml: "Ë",
  Igrave: "Ì",
  Iacute: "Í",
  Icirc: "Î",
  Iuml: "Ï",
  ETH: "Ð",
  Ntilde: "Ñ",
  Ograve: "Ò",
  Oacute: "Ó",
  Ocirc: "Ô",
  Otilde: "Õ",
  Ouml: "Ö",
  Oslash: "Ø",
  Ugrave: "Ù",
  Uacute: "Ú",
  Ucirc: "Û",
  Uuml: "Ü",
  Yacute: "Ý",
  THORN: "Þ",
  szlig: "ß",
  agrave: "à",
  aacute: "á",
  acirc: "â",
  atilde: "ã",
  auml: "ä",
  aring: "å",
  aelig: "æ",
  ccedil: "ç",
  egrave: "è",
  eacute: "é",
  ecirc: "ê",
  euml: "ë",
  igrave: "ì",
  iacute: "í",
  icirc: "î",
  iuml: "ï",
  eth: "ð",
  ntilde: "ñ",
  ograve: "ò",
  oacute: "ó",
  ocirc: "ô",
  otilde: "õ",
  ouml: "ö",
  oslash: "ø",
  ugrave: "ù",
  uacute: "ú",
  ucirc: "û",
  uuml: "ü",
  yacute: "ý",
  thorn: "þ",
  yuml: "ÿ",
  OElig: "Œ",
  oelig: "œ",
  Scaron: "Š",
  scaron: "š",
  Yuml: "Ÿ",
  fnof: "ƒ",
  circ: "ˆ",
  tilde: "˜",
  Tab: "\t",
  NewLine: "\n",
  excl: "!",
  num: "#",
  dollar: "$",
  percnt: "%",
  lpar: "(",
  rpar: ")",
  ast: "*",
  plus: "+",
  comma: ",",
  period: ".",
  sol: "/",
  colon: ":",
  semi: ";",
  equals: "=",
  quest: "?",
  commat: "@",
  lsqb: "[",
  lbrack: "[",
  bsol: "\\",
  rsqb: "]",
  rbrack: "]",
  Hat: "^",
  lowbar: "_",
  grave: "`",
  lcub: "{",
  lbrace: "{",
  verbar: "|",
  vert: "|",
  rcub: "}",
  rbrace: "}",
};

/** Entities that also decode without a trailing semicolon (legacy). */
export const LEGACY = new Set([
  "amp",
  "lt",
  "gt",
  "quot",
  "nbsp",
  "copy",
  "reg",
  "AMP",
  "LT",
  "GT",
  "QUOT",
  "COPY",
  "REG",
]);

const C1_REPLACEMENTS = {
  128: 0x20ac,
  130: 0x201a,
  131: 0x0192,
  132: 0x201e,
  133: 0x2026,
  134: 0x2020,
  135: 0x2021,
  136: 0x02c6,
  137: 0x2030,
  138: 0x0160,
  139: 0x2039,
  140: 0x0152,
  142: 0x017d,
  145: 0x2018,
  146: 0x2019,
  147: 0x201c,
  148: 0x201d,
  149: 0x2022,
  150: 0x2013,
  151: 0x2014,
  152: 0x02dc,
  153: 0x2122,
  154: 0x0161,
  155: 0x203a,
  156: 0x0153,
  158: 0x017e,
  159: 0x0178,
};

/** Decodes character references in text or attribute values. */
export function decodeEntities(s, inAttribute) {
  if (s.indexOf("&") === -1) return s;
  return s.replace(
    /&(#[xX][0-9a-fA-F]+;?|#[0-9]+;?|[A-Za-z][A-Za-z0-9]*;?)/g,
    (match, body, offset) => {
      if (body[0] === "#") {
        const hex = body[1] === "x" || body[1] === "X";
        const digits = body.slice(hex ? 2 : 1).replace(";", "");
        let cp = Number.parseInt(digits, hex ? 16 : 10);
        if (C1_REPLACEMENTS[cp]) cp = C1_REPLACEMENTS[cp];
        if (cp === 0 || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff))
          return "�";
        return String.fromCodePoint(cp);
      }
      if (body.endsWith(";")) {
        const name = body.slice(0, -1);
        const v = ENTITIES[name];
        if (v !== undefined) return v;
      }
      // Legacy: longest prefix that's a legacy entity, no semicolon.
      for (let len = Math.min(body.length, 6); len >= 2; len--) {
        const name = body.slice(0, len);
        if (LEGACY.has(name)) {
          const rest = body.slice(len);
          const nextChar = s[offset + 1 + len];
          if (
            inAttribute &&
            rest === "" &&
            nextChar !== undefined &&
            /[=A-Za-z0-9]/.test(nextChar)
          )
            return match;
          if (inAttribute && rest !== "" && /^[=A-Za-z0-9]/.test(rest))
            return match;
          return ENTITIES[name.toLowerCase()] + rest;
        }
      }
      return match;
    },
  );
}
