on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - "**.md"

permissions: {}

jobs:
  deploy-docs:
    runs-on: macos-15
    steps:
      - name: Trigger deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -f "$deploy_url"
