on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  deploy-docs:
    runs-on: macos-15
    steps:
      - name: Trigger deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -f "$deploy_url"
